name: Statistics
version: ${project.version}
main: statistics.main.Statistics
api-version: 1.14
authors: [vteven]
description: Track minecraft user statistics
commands:
  statistics:
    description: Show statistics about a player
    usage: /statistics [player name]
